import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
// import App from "./App";
// import Challenge1 from "./playground/Challenge1";
// import Challenge2 from "./playground/Challenge2";
// import Challenge3 from "./playground/Challenge3";
// import IntroState from "./states/IntroState";
// import SignInButton from "./states/Ternary";
// import NumValue from "./playground/NumValue";
// import MapMethod from "./playground/MapMethod";
import Common from "./CommonSituations/Common";
ReactDOM.render(<Common />, document.getElementById("root"));
