import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
// import App from "./App";
// import Challenge1 from "./playground/Challenge1";
// import IntroState from "./states/IntroState";
// import SignInButton from "./states/Ternary";
// import NumValue from "./playground/NumValue";
import MapMethod from "./playground/MapMethod";
ReactDOM.render(<MapMethod />, document.getElementById("root"));
