import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
// import App from "./App";
import "./playground/bbc1.jpg";
import "./playground/bbc2.jpg";
import "./playground/bbc3.jpg";
import "./playground/bbc4.jpg";
// import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Challenge1 from "./playground/Challenge1";
ReactDOM.render(<Challenge1 />, document.getElementById("root"));
